apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80
